### PR TITLE
feat: Setting to disable Style Groups

### PR DESCRIPTION
**Pull request by paavo**
A new setting to disable icon groups (like brands, or duotone). 

```
VIVOMEDIA:
  FontAwesome:
    Icon:
      disabled:
        solid: false
        light: false
        regular: false
        brands: true # Disable Brand Icons
        duotone: true # Disable Duotone Icons
```

### CODE REVIEW

**Comment by dlubitz** [comment]
Thanks  @paavo for this contribution. 
I'd change the logic there and set up the "enabled" styles. We just need to set up the default styles.

```
VIVOMEDIA:
  FontAwesome:
    Icon:
      styles:
        solid: true
        light: true
        regular: true
        brands: false # Disable Brand Icons
        duotone: false # Disable Duotone Icons

```

**Comment by paavo** [comment]
> I'd change the logic there and set up the "enabled" styles. We just need to set up the default styles.

This was my first idea too, but this is breaking change as now all styles are supported by default.

**Comment by dlubitz** [comment]
> We just need to set up the default styles.

That's why we need to set up the default styles in the configuration of the package (https://github.com/VIVOMEDIA/neos-fontawesome-icon/blob/main/Configuration/Settings.yaml#L5).

**Comment by dlubitz** [comment]
Thanks @paavo and sorry for leave at lying aroud that long.

I'll just change to logic to "enabled" styles.

**Pull request merged**
